openapi: 3.0.3
info:
  title: Paypal Subscriptions Authorizations Disputes-Actions API
  description: You can use billing plans and subscriptions to create subscriptions that process recurring PayPal payments for physical or digital goods, or services. A plan includes pricing and billing cycle information that defines the amount and frequency of charge for a subscription. You can also define a fixed plan, such as a $5 basic plan or a volume- or graduated-based plan with pricing tiers based on the quantity purchased. For more information, see <a href="/docs/subscriptions/">Subscrip[...]
  version: '1.6'
  contact: {}
servers:
- url: https://api-m.sandbox.paypal.com
  description: PayPal Sandbox Environment
- url: https://api-m.paypal.com
  description: PayPal Live Environment
tags:
- name: Disputes-Actions
  description: Use the `/disputes` resource with a dispute ID and an action to:<ul><li>Accept a claim.</li><li>Accept an offer to resolve a dispute.</li><li>Acknowledge the return of an item related to a dispute.</li><li>Settle a dispute.</li><li>Appeal a dispute.</li><li>Cancel a dispute.</li><li>Change the reason for a dispute.</li><li>Deny an offer to resolve dispute.</li><li>Escalate a dispute to a claim.</li><li>Make an offer to resolve a dispute.</li><li>Make an offer to resolve a dispute.[...]
paths:
  /v1/customer/disputes/{id}/provide-evidence:
    post:
      summary: Paypal Provide evidence
      description: Provides evidence for a dispute, by ID. A merchant can provide evidence for disputes with the <code>WAITING_FOR_SELLER_RESPONSE</code> status while customers can provide evidence for disputes with the <code>WAITING_FOR_BUYER_RESPONSE</code> status. Evidence can be a proof of delivery or proof of refund document or notes, which can include logs. A proof of delivery document includes a tracking number while a proof of refund document includes a refund ID. For other evidence type[...]
      operationId: disputes.provide-evidence
      security:
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-seller
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-buyer
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-partner
      tags:
      - Disputes-Actions
  /v1/customer/disputes/{id}/appeal:
    post:
      summary: Paypal Appeal dispute
      description: Appeals a dispute, by ID. To appeal a dispute, use the <code>appeal</code> link in the <a href="/docs/api/reference/api-responses/#hateoas-links/">HATEOAS links</a> from the show dispute details response. If this link does not appear, you cannot appeal the dispute. Submit new evidence as a document or notes in the JSON request body. For constraints and rules regarding documents, see <a href="/docs/integration/direct/customer-disputes/integration-guide/#documents">documents</a>[...]
      operationId: disputes.appeal
      security:
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-seller
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-buyer
      tags:
      - Disputes-Actions
  /v1/customer/disputes/{id}/accept-claim:
    post:
      summary: Paypal Accept claim
      description: Accepts liability for a claim, by ID. When you accept liability for a claim, the dispute closes in the customer’s favor and PayPal automatically refunds money to the customer from the merchant's account. Allowed accept_claim_type values for the request is available in dispute details <a href="/docs/api/customer-disputes/v1/#definition-allowed_response_options">allowed response options</a> object.
      operationId: disputes.accept-claim
      security:
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-seller
      tags:
      - Disputes-Actions
  /v1/customer/disputes/{id}/adjudicate:
    post:
      summary: Paypal Settle dispute
      description: <blockquote><strong>Important:</strong> This method is for sandbox use only.</blockquote> Settles a dispute in either the customer's or merchant's favor. Merchants can make this call in the sandbox to complete end-to-end dispute resolution testing, which mimics the dispute resolution that PayPal agents normally complete. To make this call, the dispute <code>status</code> must be <code>UNDER_REVIEW</code> and <code>adjudicate</code> link  should be available in the <a href="/do[...]
      operationId: disputes.adjudicate
      security:
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-seller
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-buyer
      tags:
      - Disputes-Actions
  /v1/customer/disputes/{id}/require-evidence:
    post:
      summary: Paypal Update dispute status
      description: <blockquote><strong>Important:</strong> This method is for sandbox use only.</blockquote> Updates the status of a dispute, by ID, from <code>UNDER_REVIEW</code> to either:<ul><li><code>WAITING_FOR_BUYER_RESPONSE</code></li><li><code>WAITING_FOR_SELLER_RESPONSE</code></li></ul>This status change enables either the customer or merchant to submit evidence for the dispute. To make this call, the dispute <code>status</code> must be <code>UNDER_REVIEW</code> and <code>require-eviden[...]
      operationId: disputes.require-evidence
      security:
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-seller
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-buyer
      tags:
      - Disputes-Actions
  /v1/customer/disputes/{id}/escalate:
    post:
      summary: Paypal Escalate dispute to claim
      description: Escalates the dispute, by ID, to a PayPal claim. To make this call, the stage in the dispute lifecycle must be `INQUIRY`.
      operationId: disputes.escalate
      security:
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-seller
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-buyer
      tags:
      - Disputes-Actions
  /v1/customer/disputes/{id}/send-message:
    post:
      summary: Paypal Send message about dispute to other party
      description: Sends a message about a dispute, by ID, to the other party in the dispute. Merchants and customers can only send messages if the `dispute_life_cycle_stage` value is `INQUIRY`. For constraints and rules regarding documents that can be attached as part of the message, see <a href="/docs/integration/direct/customer-disputes/integration-guide/#documents">documents</a>. To send a message, use the <code>send-message</code> link in the <a href="/docs/api/reference/api-responses/#hate[...]
      operationId: disputes.send-message
      security:
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-seller
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-buyer
      tags:
      - Disputes-Actions
  /v1/customer/disputes/{id}/make-offer:
    post:
      summary: Paypal Make offer to resolve dispute
      description: Makes an offer to the other party to resolve a dispute, by ID. To make this call, the stage in the dispute lifecycle must be `INQUIRY`. If the customer accepts the offer, PayPal automatically makes a refund. Allowed offer_type values for the request is available in dispute details <a href="/docs/api/customer-disputes/v1/#definition-allowed_response_options">allowed response options</a> object.
      operationId: disputes.make-offer
      security:
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-seller
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-buyer
      tags:
      - Disputes-Actions
  /v1/customer/disputes/{id}/accept-offer:
    post:
      summary: Paypal Accept offer to resolve dispute
      description: The customer accepts the offer from merchant to resolve a dispute, by ID. PayPal automatically refunds the amount proposed by merchant to the customer.
      operationId: disputes.accept-offer
      security:
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-buyer
      tags:
      - Disputes-Actions
  /v1/customer/disputes/{id}/deny-offer:
    post:
      summary: Paypal Deny offer to resolve dispute
      description: Denies an offer that the merchant proposes for a dispute, by ID.
      operationId: disputes.deny-offer
      security:
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-buyer
      tags:
      - Disputes-Actions
  /v1/customer/disputes/{id}/acknowledge-return-item:
    post:
      summary: Paypal Acknowledge returned item
      description: Acknowledges that the customer returned an item for a dispute, by ID. A merchant can make this request for disputes with the `MERCHANDISE_OR_SERVICE_NOT_AS_DESCRIBED` reason. Allowed acknowledgement_type values for the request is available in dispute details <a href="/docs/api/customer-disputes/v1/#definition-allowed_response_options">allowed response options</a> object. For constraints and rules regarding documents, see <a href="/docs/integration/direct/customer-disputes/inte[...]
      operationId: disputes.acknowledge-return-item
      security:
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-seller
      tags:
      - Disputes-Actions
  /v1/customer/disputes/{id}/provide-supporting-info:
    post:
      summary: Paypal Provide supporting information for dispute
      description: Provides supporting information for a dispute, by ID. A merchant or buyer can make this request for disputes if they find the `provide-supporting-info` link in the HATEOAS links in the list disputes response. The party can provide the supporting information to PayPal to defend themselves only when the `dispute_life_cycle_stage` is `CHARGEBACK`, `PRE_ARBITRATION`, or `ARBITRATION`. They can provide a note that describes their part with details or upload any supporting documents[...]
      operationId: disputes.provide-supporting-info
      security:
      - Oauth2:
        - https://uri.paypal.com/services/disputes/update-seller
        - https://uri.paypal.com/services/disputes/update-buyer
        - https://uri.paypal.com/services/disputes/update-partner
      tags:
      - Disputes-Actions
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 authentication
      flows:
        clientCredentials:
          tokenUrl: /v1/oauth2/token
          scopes:
            https://uri.paypal.com/services/subscriptions: Manage plan & subscription